<?php
/**
 * TimezoneResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  GoogleMaps
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Google Maps API
 *
 * Google Maps API Integration
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace GoogleMaps;

use PHPUnit\Framework\TestCase;

/**
 * TimezoneResponseTest Class Doc Comment
 *
 * @category    Class
 * @description TimezoneResponse
 * @package     GoogleMaps
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class TimezoneResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "TimezoneResponse"
     */
    public function testTimezoneResponse()
    {
    }

    /**
     * Test attribute "dst_offset"
     */
    public function testPropertyDstOffset()
    {
    }

    /**
     * Test attribute "raw_offset"
     */
    public function testPropertyRawOffset()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "time_zone_id"
     */
    public function testPropertyTimeZoneId()
    {
    }

    /**
     * Test attribute "time_zone_name"
     */
    public function testPropertyTimeZoneName()
    {
    }

    /**
     * Test attribute "error_message"
     */
    public function testPropertyErrorMessage()
    {
    }
}
